version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: sdit_postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 180903
      POSTGRES_DB: sdit_management
    volumes:
      - sdit_postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: sdit_backend
    ports:
      - "8081:8080"
    environment:
      - PORT=${PORT:-8080}
      - DB_HOST=${DB_HOST:-postgres}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-180903}
      - DB_NAME=${DB_NAME:-sdit_management}
      - DB_PORT=${DB_PORT:-5432}
      - JWT_SECRET=${JWT_SECRET:-secret}
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: sdit_frontend
    ports:
      - "3001:80"
    depends_on:
      - backend

volumes:
  sdit_postgres_data:
